name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '18'

      - name: Set Git Identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clean gh-pages Branch
        run: |
          git fetch
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
            git rm -rf .
            git commit -m "Clean gh-pages branch"
          else
            git checkout --orphan gh-pages
            git rm -rf .
            git commit --allow-empty -m "Initial gh-pages commit"
          fi

      - name: Copy src to gh-pages
        run: |
          git checkout main
          mkdir -p ../temp/
          cp -r src/* ../temp/
          git checkout gh-pages
          cp -r ../temp/* .
          git add .
          git commit -m "Update gh-pages branch"
          git push -f origin gh-pages